# Neural Networks with Numpy



## Contents
0. Install packages
1. My first neural network
2. An inproved neural net


## 0. Install packages

In [ ]:
%pip install numpy
%pip install keras
%pip install tensorflow
%pip install wget

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


## 1. My first neural network simply using numpy
source: https://www.youtube.com/watch?v=kft1AJ9WVDk

In [1]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

training_inputs = np.array([[0,0,1],
                           [1,1,1],
                           [1,0,1],
                           [0,1,1]])

training_outputs = np.array([[0,1,1,0]]).T

np.random.seed(1)

synaptic_weights = 2 + np.random.random((3,1)) - 1

print('Random starting synaptic weights: ')
print(synaptic_weights)

for iteration in range (1000):
    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    
print('outputs')
print(outputs)

Random starting synaptic weights: 
[[1.417022  ]
 [1.72032449]
 [1.00011437]]
outputs
[[0.73108107]
 [0.98428749]
 [0.91812474]
 [0.93822198]]


## 2. An improved neural net
With sigmoid_derivative 

In [13]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return  x * (1-x)

training_inputs = np.array([[0,0,1],
                           [1,1,1],
                           [1,0,1],
                           [0,1,1]])

training_outputs = np.array([[0,1,1,0]]).T

np.random.seed(1)

synaptic_weights = 2 + np.random.random((3,1)) - 1

print('Random starting synaptic weights: ')
print(synaptic_weights)

for iteration in range (50000):
    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    
    error = training_outputs - outputs
    
    adjustments = error * sigmoid_derivative(outputs)
    
    synaptic_weights += np.dot(input_layer.T, adjustments)

print('Synaptic weights after training')
print(synaptic_weights)
    
print('Outputs after trainig')
print(outputs)

Random starting synaptic weights: 
[[1.417022  ]
 [1.72032449]
 [1.00011437]]
Synaptic weights after training
[[11.30928823]
 [-0.2049903 ]
 [-5.45009058]]
Outputs after trainig
[[0.00427758]
 [0.99650944]
 [0.99715456]
 [0.00348752]]
