# Pytorch

## Contents
0. Install packages
1. My first torch tensor
2. Torchvision


Source: Sentdex
- Video 1: https://www.youtube.com/watch?v=BzcBsTou0C0
- Video 2: https://www.youtube.com/watch?v=i2yPxY2rOzs

Source: Pytorch in 60 minutes: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

## 0. Install packages

please see https://pytorch.org/get-started/locally/ how to install your version of orch

In [9]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [5]:
!conda install pytorch torchvision torchaudio -c pytorch

Solving environment: | 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/noarch::holoviews==1.14.8=pyhd3eb1b0_0
  - defaults/osx-64::notebook==6.4.8=py39hecd8cb5_0
  - defaults/noarch::requests-file==1.5.1=pyhd3eb1b0_0
  - defaults/noarch::smart_open==5.1.0=pyhd3eb1b0_0
  - defaults/noarch::nbclassic==0.3.5=pyhd3eb1b0_0
  - defaults/osx-64::jupyter==1.0.0=py39hecd8cb5_7
  - defaults/noarch::cookiecutter==1.7.3=pyhd3eb1b0_0
  - defaults/noarch::itemloaders==1.0.4=pyhd3eb1b0_1
  - defaults/noarch::google-cloud-core==1.7.1=pyhd3eb1b0_0
  - defaults/osx-64::anaconda==2022.05=py39_0
  - defaults/noarch::datashader==0.13.0=pyhd3eb1b0_1
  - defaults/noarch::conda-repo-cli==1.0.4=pyhd3eb1b0_0
  - defaults/osx-64::conda-build==3.21.8=py39hecd8cb5_2
  - defaults/osx-64::parsel==1.6.0=py39hecd8cb5_0
  - defaults/noarch::sphinx==4.4.0=pyhd3eb1b0_0
  - defaults/osx-64::ipython==8.2.0=py39hecd8cb5_0
  - defau

## 1. My first torch tensor

In [7]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y) # multiply the two arrays tensor is a multidimensional array

ImportError: dlopen(/Users/michielbontenbal/opt/anaconda3/lib/python3.9/site-packages/torch/_C.cpython-39-darwin.so, 0x0002): Library not loaded: '@loader_path/libtorch_cpu.dylib'
  Referenced from: '/Users/michielbontenbal/opt/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_python.dylib'
  Reason: tried: '/Users/michielbontenbal/opt/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib' (no such file), '/usr/local/lib/libtorch_cpu.dylib' (no such file), '/usr/lib/libtorch_cpu.dylib' (no such file)

In [4]:
x = torch.zeros([2,5])

In [5]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [6]:
x.shape

torch.Size([2, 5])

In [8]:
y = torch.rand([2,5])
y

tensor([[0.8045, 0.1309, 0.6837, 0.9797, 0.1849],
        [0.0862, 0.2665, 0.3092, 0.5778, 0.7307]])

### Reshaping in Numpy => view in Pytorch

In [9]:
y.view([1,10])

tensor([[0.8045, 0.1309, 0.6837, 0.9797, 0.1849, 0.0862, 0.2665, 0.3092, 0.5778,
         0.7307]])